name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: python -m pip install --upgrade pip

    - name: lint and test
      run: |
        pip install -q flake8
        flake8
        python setup.py install
        q2lint
